// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD59PHIEDYubpmhuUA-4zLyBGF2YregY4',
    appId: '1:172254087018:web:890d51e007a2203cb28713',
    messagingSenderId: '172254087018',
    projectId: 'nutricion-81db6',
    authDomain: 'nutricion-81db6.firebaseapp.com',
    databaseURL: 'https://nutricion-81db6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'nutricion-81db6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5Ycy9E-bu7eAgUpV0IGRcXcpQ4z8nEHs',
    appId: '1:172254087018:android:1ef58eeadb305e19b28713',
    messagingSenderId: '172254087018',
    projectId: 'nutricion-81db6',
    databaseURL: 'https://nutricion-81db6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'nutricion-81db6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqeIIZHi8uJo9o_xuZlAPFrC5nlQ551TU',
    appId: '1:172254087018:ios:7fe0ab08fe843797b28713',
    messagingSenderId: '172254087018',
    projectId: 'nutricion-81db6',
    databaseURL: 'https://nutricion-81db6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'nutricion-81db6.appspot.com',
    iosBundleId: 'com.example.nutriapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqeIIZHi8uJo9o_xuZlAPFrC5nlQ551TU',
    appId: '1:172254087018:ios:7fe0ab08fe843797b28713',
    messagingSenderId: '172254087018',
    projectId: 'nutricion-81db6',
    databaseURL: 'https://nutricion-81db6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'nutricion-81db6.appspot.com',
    iosBundleId: 'com.example.nutriapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDD59PHIEDYubpmhuUA-4zLyBGF2YregY4',
    appId: '1:172254087018:web:3db36e54c04de17cb28713',
    messagingSenderId: '172254087018',
    projectId: 'nutricion-81db6',
    authDomain: 'nutricion-81db6.firebaseapp.com',
    databaseURL: 'https://nutricion-81db6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'nutricion-81db6.appspot.com',
  );

}